### ISSUE TITLE
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

### ISSUE THREAD

**Issue by anukul** [boltgolt/howdy#97]
_Please describe the issue in as much detail as possible, including any errors and traces_

The error is - VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

howdy add - https://asciinema.org/a/ihNgoNb97s3wxTIPZWAnItt3D

```
$ sudo howdy add
Adding face model for the user anukul
Enter a label for this new model [Initial model]: 
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 90, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 117, in <module>
    enc = face_recognition.face_encodings(frame)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 199, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 153, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.fhog_object_detector, image: array, upsample_num_times: int=0) -> dlib.rectangles

Invoked with: <dlib.fhog_object_detector object at 0x7fd0819462d0>, None, 1
```

howdy test - https://asciinema.org/a/55hG9CnCcU6QQFfzEvHrkGQmz
```
$ sudo howdy test
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 102, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 85, in <module>
    overlay = frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):
Ubuntu 18.04.1 on Dell XPS 9370

Howdy version:
2.4.0

**Comment by janhancic** [comment]
I get the same error:

```
$ sudo howdy test
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 102, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 85, in <module>
    overlay = frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

I'm on Ubuntu 18.10 using Dell XPS 13 (9370 or 2018 version).

This is right after running the installation. What can I do to help debug & solve this issue?

**Comment by janhancic** [comment]
I've tried changing howdy's configuration to use a different webcam (my system lists 4 even though I've only got the built in one). If I switch to another I get this:

```
$ sudo howdy test
Unable to stop the stream: Invalid argument

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 102, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 85, in <module>
    overlay = frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by janhancic** [comment]
I found #81 ... so following your suggsestion I ran

```
$ dmesg | grep "Unknown video format" 
[   21.089178] uvcvideo: Unknown video format 00000032-0002-0010-8000-00aa00389b71
```

which would mean that there is a driver issue, and there doesn't seem to be a linux driver for my IR camera :(
I would like to get this working with the normal camera at least tho.

Btw I did see the red lights flashing during setup.

**Comment by anukul** [comment]
Oh, I also saw the lights.

But, then there's this

```bash
$  dmesg | grep "Unknown video format"
[    2.479991] uvcvideo: Unknown video format 00000032-0002-0010-8000-00aa00389b71
```

So I guess 9370 isn't supported yet.

**Comment by janhancic** [comment]
@boltgolt do you want me to open a different issue for the other problem here (i.e. can't use th enormal webcam)?

**Comment by boltgolt** [comment]
There have been reports (on github and elsewhere) of IR camera drivers working after upgrading to kernel 4.19. You can run `uname -r` to see your current version, but updating differs wildly between distros and might not be pleasant. 

@janhancic please do, as it's not relevant to this issue specifically.

**Comment by janhancic** [comment]
Thanks, will open a new issue once I'm home behind my laptop.

And thanks for the kernel tip, might venture that too. Have to learn how to do it at some point anyway :)

**Comment by janhancic** [comment]
@boltgolt so I found this trick that you mentioned in #60 `sudo QT_X11_NO_MITSHM=1 howdy test`, and this makes the test command work! Is there a way to make the test command work without this workaround however?

Also, I don't know if the above fixed the issue or if I was just being silly before. But one of my cameras now actually works. I was able to add a model and now am able to use Howdy! Thanks, it's amazing!

I will probably still try the new kernel version as I'd really like to get the IR camera working too.

**Comment by boltgolt** [comment]
I've edited my original answer on that thread to include a more permanent (untested) fix, hope that helps. Or shouldn't fix your camera issue but good to hear it's finally semi-working!

**Comment by a-pushkin** [comment]
Ran into the same issue with Ubuntu 18.04/Kernel 4.19 and Logitech BRIO. Neither of the workarounds seemed to work.
`andrei@andrei-desktop:~$ sudo howdy add
No face model folder found, creating one
Adding face model for the user andrei
Enter a label for this new model [Initial model] (max 24 characters): 
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11147
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11147: error: (-215) scn == 3 || scn == 4 in function cvtColor

andrei@andrei-desktop:~$ uname -r
4.19.0-041900-lowlatency
andrei@andrei-desktop:~$ sudo QT_X11_NO_MITSHM=1 howdy test
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11147
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 101, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 109, in <module>
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11147: error: (-215) scn == 3 || scn == 4 in function cvtColor
`

**Comment by boltgolt** [comment]
Could you post the output of the following commands?  

```
dmesg | grep "Unknown video format"
v4l2-ctl --list-formats
```

**Comment by mattivilola** [comment]
I've got the same issue on my Dell XPS13 9370. I can see red ir lights upon installation but same error message. Some logs for your information if it helps. The above QT_X11_NO_MITSHM=1 flag did not help.

➜  ~ v4l2-ctl --list-formats   

ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2

➜  ~ dmesg | grep "Unknown video format"
[    2.546759] uvcvideo: Unknown video format 00000032-0002-0010-8000-00aa00389b71

**Comment by boltgolt** [comment]
@mattivilola your issue should be fixed by upgrading to >4.19, `00000032-0002-0010-8000-00aa00389b71` is Mircosoft 8 bit IR format

**Comment by mattivilola** [comment]
> @mattivilola your issue should be fixed by upgrading to >4.19, `00000032-0002-0010-8000-00aa00389b71` is Mircosoft 8 bit IR format

Thanks for the response. Fixed! Updated kernel to above 4.19 and problem solved.

**Comment by a-pushkin** [comment]
> v4l2-ctl --list-formats
```
andrei@andrei-desktop:~/Downloads$ dmesg | grep "Unknown video format"
[    6.400718] uvcvideo: Unknown video format 00000032-0002-0010-8000-00aa00389b71
andrei@andrei-desktop:~/Downloads$ v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG

	Index       : 2
	Type        : Video Capture
	Pixel Format: 'NV12'
	Name        : Y/CbCr 4:2:0
```

**Comment by boltgolt** [comment]
@a-pushkin see my response just above

**Comment by a-pushkin** [comment]
I upgraded to mainline 4.20. smesg is now clean. However adding a face still fails:
```
andrei@andrei-desktop:~$ sudo howdy add
No face model known
[sudo] password for andrei: 
No face model folder found, creating one
Adding face model for the user andrei
Enter a label for this new model [Initial model] (max 24 characters): 
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11147
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11147: error: (-215) scn == 3 || scn == 4 in function cvtColor

andrei@andrei-desktop:~$ dmesg | grep "Unknown video format"
andrei@andrei-desktop:~$ 
```
